#!/bin/bash

source $HOME/.bashrc

while :

do

(echo ${WALLET_PASS}) | $BINARY tx distribution withdraw-rewards $valoper --from $address --fees 500$DENOM --commission --chain-id $CHAIN -y

sleep 5

balance=`$BINARY q bank balances $address -o json | jq -r .balances[].amount`

stake=$(($balance-2000))

sleep 5

(echo ${WALLET_PASS}) | $BINARY tx staking delegate $valoper ${stake}`echo $DENOM` --from $address --chain-id $CHAIN --fees 555$DENOM -y

sleep 300

done
